#!/usr/bin/env bash
# display "to infinity and beyond" with sleep 2 and iam invicible!!! when receiving a SIGTERM signal

trap "echo 'I am invincible!!!'" SIGTERM
while true
do
	echo "To infinity and beyond"
	sleep 2
done
