#!/usr/bin/env bash
# This script display loops 1 to 10 on the 4th bad luck, on the 8th good luck and on other Besto School

counter=1
while [[ "$counter" -le 10 ]]
do
	if [[ "$counter" -eq 4 ]]
	then 
		echo "bad luck"
	elif [[ "$counter" -eq 8 ]]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((counter=counter+1))
done
