#!/usr/bin/env bash
# This script display  number from 1 t0 20, on 4th  4 and bad luck from china , on 9th 9 and bad luck from japan
# on 17th bad luck from italy

counter=1
while [[ "$counter" -le 20 ]]
do
	case "$counter" in 

		4)
			echo "$counter"
			echo "bad luck from China"
			;;
		9)
			echo "$counter"
			echo "bad luck from Japan"
			;;
		17)
			echo "$counter"
			echo "bad luck from Italy"
			;;
		*)
			echo "$counter"
			;;
	esac
	((counter=counter+1))
done
